### ISSUE TITLE
Video is not zooming/rotating

### ISSUE THREAD

**Issue by liutingdu** [xbgmsharp/videojs-rotatezoom#1]
Hi,

Thanks for sharing the code. 

I am not sure this is the right place to ask this question, I cloned the code and open index.html from Chrome and I am expecting the video to be zoomed (1.5 )and rotated (90), but it's just playing the original video without changing anything. Am I missing something? 

Thanks a lot,
Liuting

**Comment by xbgmsharp** [comment]
Are you using the HTML5 player or the flash fallback.
It won't work when using the flash fallback.
The sample is now fixed via 1ef4efb9e3a95f58d2300eda1b251eaa76b4228f
The plugin name change and the sample was not being updated

**Comment by liutingdu** [comment]
I was just trying to run the sample. It works now! Thank you for the fast reply :)
